name: Telegram Bot Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # You can specify your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Deploy Bot
        run: npm start  # Replace with your deployment command
